language: python
services:
  - docker

jobs:
  include:
    - stage: security
      before_script:
        - sudo make install-vulnerabilities-checker
      script:
        - make check-vulnerabilities
    - stage: documentation
      script:
        - make build-docs
      deploy:
        provider: script
        script: ls -al
