language: minimal
dist: bionic
services:
  - docker
install: skip
stages:
  - scan
  - build
  - deploy

jobs:
  include:
    ################
    ### SECURITY ###
    ################
    - stage: scan
      language: minimal
      before_script:
        - sudo make install-vulnerabilities-checker
      script:
        - make check-vulnerabilities
    #####################
    ### Build docs ###
    #####################
    - stage: build
      language: minimal
      script:
        - make build-docs
        - cp ./odahu-docs.pdf ./out/odahu-docs.pdf
    ###################
    ### Upload docs ###
    ###################
    - stage: push
      provider: pages
      skip_cleanup: true
      github_token: $TRAVIS_GITHUB_SECRET
      keep_history: true
      local_dir: out
      repo: odahu/docs.odahu.org
      target_branch: dh_pages
      email: gh-docs@odahu.org
      name: "odahu-docs Publisher"
      on:
        branch: feat/travis

