version: 2.1
jobs:
  security-check:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo make install-vulnerabilities-checker
      - run: make check-vulnerabilities
  build:
    environment:
      SHORT_VERSION: ${CIRCLE_BRANCH}
      FULL_VERSION: ${CIRCLE_BRANCH}
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Build docs
          command: |
            make build-docs
            sudo cp ./odahu-docs.pdf ./out/odahu-docs.pdf
      - persist_to_workspace:
          root: .
          paths:
            - out
  deploy:
    docker:
      - image: circleci/node:12.20
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "88:79:7f:50:24:5c:b6:00:49:ac:b4:e6:ae:4b:ab:7a"
      - run:
          name: Setup gh-pages
          command: |
            sudo npm install -g --silent gh-pages@3.1.0
            git config --global user.email "gh-docs@odahu.org"
            git config --global user.name "odahu-docs Publisher"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages --branch 'master' --repo "odahu/docs.odahu.org" --dist "out/"

workflows:
  main:
    jobs:
      - security-check
      - build:
          requires:
            - security-check
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /release\/(\d\.){2}\d$/
            tags:
              only: /(\d\.){2}\d$/
