version: 2.1
jobs:
  security-check:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo make install-vulnerabilities-checker
      - run: make check-vulnerabilities
  build:
    environment:
      SHORT_VERSION: ${CIRCLE_BRANCH}
      FULL_VERSION: ${CIRCLE_BRANCH}
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Build docs
          command: |
            make build-docs
            sudo cp ./odahu-docs.pdf ./out/odahu-docs.pdf
      - persist_to_workspace:
          root: .
          paths:
            - out
  deploy:
    environment:
      VERSION: ${CIRCLE_BRANCH}
      CACHE_DIR: cache
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "88:79:7f:50:24:5c:b6:00:49:ac:b4:e6:ae:4b:ab:7a"
      - run: ssh-keyscan ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy docs
          command: |
            git clone git@github.com:odahu/docs.odahu.epam.com.git
            cp -r out/* docs.odahu.org/
            cp -r out/.[^.]* docs.odahu.org/
            cd docs.odahu.org
            git config user.email "gh-docs@odahu.org"
            git config user.name "odahu-docs Publisher"
            git commit -am '${VERSION}'
            git push origin master

workflows:
  main:
    jobs:
      - security-check
      - build:
          requires:
            - security-check
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /release\/(\d\.){2}\d$/
            tags:
              only: /(\d\.){2}\d$/
